#! /usr/bin/env bash

# also, to facilitate deployment to s3 on push, add a shell script to
# .git/hooks/pre-push containing:
# ./deploy-to-s3

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd );
pushd $SCRIPT_DIR;

echo "pushing to S3..."
dotclean.js .
aws s3 sync --profile "brettonw-iR" . s3://astro-website-bucket --delete --exclude "*" --include "img/*" --include "textures/*" --include "shaders/*" --include "modules/*" --include "data/*" --include "index.html" --include "*.css" --acl public-read

echo "invalidating distribution to force cache refresh...";
aws cloudfront create-invalidation --profile "brettonw-iR" --distribution-id E2WDSW49W7014M --paths "/*"

popd;
